copy packages

diff --git a/eng/pipelines/cadl-ci.yml b/eng/pipelines/cadl-ci.yml
--- a/eng/pipelines/cadl-ci.yml
+++ b/eng/pipelines/cadl-ci.yml
@@ -79,9 +79,14 @@ stages:
         - pwsh: ./eng/CaldEmitterUT.ps1
           displayName: 'Unit_Test for CADL emitter'
           workingDirectory: $(Build.SourcesDirectory)
+        - script: |
+            mkdir -p $(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/packages
+            cp azure-tools-cadl-csharp-*.tgz $(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/packages/
+          displayName: 'Copy CADL Csharp emitter library to staging dir'
+          workingDirectory: $(Build.SourcesDirectory)/src/CADL.Extension/Emitter.Csharp
         - task: PublishBuildArtifacts@1
           inputs:
-            PathtoPublish: '$(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)'
+            PathtoPublish: '$(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/packages'
             ArtifactName: '$(VAR_ARTIFACT_NAME)'
   - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
     - stage: 'Release'
@@ -117,10 +122,10 @@ stages:
 
             echo -e "\e[32m[$(date -u)] LOG: publish the package"
             echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" >> ~/.npmrc
-            for file in $(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/$(VAR_ARTIFACT_NAME)/$(VAR_ARTIFACT_NAME)/*.tgz
+            for file in $(VAR_BUILD_ARTIFACT_STAGING_DIRECTORY)/$(VAR_ARTIFACT_NAME)/*.tgz
             do
               echo -e "\e[32m[$(date -u)] LOG: File: $file"
-              npm publish $file --access public || { echo 'publish $file failed' ; }
+              npm publish $file --access public || { echo "publish $file failed" ; exit 1; }
             done
             rm ~/.npmrc || { echo 'rm ~/.npmrc failed' ; exit 1; }
           displayName: Publish
